/**:
  ros__parameters:
    camera_name: "camera_1"
    frame_id: "camera_top/camera_link"
    pixel_format: bgr8
    serial_no: 210900907
    camera_info_url: "file:///home/volt/projects/autoware/src/sensor_component/external/lucid_vision_driver/config/camera_front_half.yaml"
    fps: 15
    horizontal_binning: 2 # resize horizontal resolution/horizontal_binning
    vertical_binning: 2 # resize horizontal resolution/vertical_binning
    use_default_device_settings: true
    # if you use_default_device_settings: true, the following settings are ignored.
    # ROS driver will use the default device settings of the camera.
    exposure_auto: true
    exposure_target: 187
    gain_auto: true
    gain_target: 1
    gamma_target: 1.0
